---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/7/15 16:03
---

local this = {}

function this.OnAwake(rootUi)
    this.GameObject = rootUi.gameObject
    this.Transform = rootUi.transform
    XTool.InitUiObject(this)
    this.AutoAddListeners()
end

function this.AutoAddListeners()
    this.BtnTanchuangClose.onClick:AddListener(this.CloseLoginType)
    this.BtnConfirm.onClick:AddListener(this.OnConfirm)
    this.BtnClose.onClick:AddListener(this.OnCancel)
end

function this.Open(callback)
    this.GameObject:SetActiveEx(true)
    this.ConfirmCallback = callback
end

function this.OnConfirm()
    if this.ConfirmCallback ~= nil then
        this.ConfirmCallback()
        this.ConfirmCallback = nil
    end
    this.CloseLoginType()
end

function this.OnCancel()
    this.ConfirmCallback = nil
    this.CloseLoginType()
end

function this.CloseLoginType()
    this.GameObject:SetActiveEx(false)
end

return this