---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/7/15 15:04
---
local this = XLuaUiManager.Register(XLuaUi, "UiLoginAgreement")
local LoginAgreePanel = require("XUi/XUiLogin/XUiLoginAgreePanel")

function this:OnAwake()
    LoginAgreePanel.OnAwake(self.Transform:Find("SafeAreaContentPane/PanelAgreement").gameObject, self)
end

function this:OnStart(cb)
    LoginAgreePanel.Show()
    self.CloseCallBack = cb
end