---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/15 18:13
---

---@class XGoldenMinerComponentSunMoon:XEntity
---@field _OwnControl XGoldenMinerGameControl
---@field _ParentEntity XGoldenMinerEntityStone
local XGoldenMinerComponentSunMoon = XClass(XEntity, "XGoldenMinerComponentSunMoon")

--region Override
function XGoldenMinerComponentSunMoon:OnInit()
    self.SunMoonType = XEnumConst.GOLDEN_MINER.STONE_SUN_MOON_TYPE.NORMAL
    self.StoneRealType = XEnumConst.GOLDEN_MINER.STONE_SUN_MOON_REAL_TYPE.NONE
    self.RealRoot = nil
    self.VirtualRoot = nil
    self.CanInteraction = true
end

function XGoldenMinerComponentSunMoon:OnRelease()
    self.RealRoot = nil
    self.VirtualRoot = nil
    self.StoneRealType = XEnumConst.GOLDEN_MINER.STONE_SUN_MOON_REAL_TYPE.NONE
    self.SunMoonType = XEnumConst.GOLDEN_MINER.STONE_SUN_MOON_TYPE.NORMAL
    self.CanInteraction = true
end
--endregion

function XGoldenMinerComponentSunMoon:SetRealRoot(value)
    self.RealRoot = value
end

function XGoldenMinerComponentSunMoon:SetVirtualRoot(value)
    self.VirtualRoot = value
end

return XGoldenMinerComponentSunMoon