---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 11:04
---

---@class XUiNonogramGridBoomNum
local XUiNonogramGridBoomNum = XClass(nil, "UiNonogramGridBoomNum")

function XUiNonogramGridBoomNum:Ctor(ui, parentUi)
    self.ParentUi = parentUi
    XUiHelper.InitUiClass(self, ui)
end

function XUiNonogramGridBoomNum:SetBoomCount(count)
    self.TxtNum.text = count
end

function XUiNonogramGridBoomNum:SetImgUnknownActive(isActive)
    self.TxtNum.gameObject:SetActiveEx(not isActive)
end

return XUiNonogramGridBoomNum