local XUiButtonLongClick = require("XUi/XUiCommon/XUiButtonLongClick")
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 11:04
---

---@class XUiNonogramGridBlock:XUiNode
---@field _Control XNonogramControl
local XUiNonogramGridBlock = XClass(XUiNode, "UiNonogramGridBlock")

function XUiNonogramGridBlock:OnAwake()

end

function XUiNonogramGridBlock:OnStart(rowIndex, colIndex, panelBlockTrans, uiCamera)
    self.RowIndex = rowIndex
    self.ColIndex = colIndex
    self.PanelBlockTrans = panelBlockTrans
    self.UiCamera = uiCamera
    --self.BtnGridBlock.CallBack = handler(self, self.OnBtnGridBlockClick)
    self.Status = XEnumConst.Nonogram.NonogramGridBlockStatus.None

    self:InitPointer()
end

function XUiNonogramGridBlock:OnDestroy()

end

function XUiNonogramGridBlock:InitPointer()
    XUiButtonLongClick.New(self.UiPointer, 10, self, self.OnBtnGridBlockClick, self.OnBtnGridBlockLongClicked, nil, false)
    self.UiPointer:AddPointerDownListener(function()
        self.Parent.IsCanSliderClick = true
    end)
end

function XUiNonogramGridBlock:OnBtnGridBlockClick()
    if self.Status ~= XEnumConst.Nonogram.NonogramGridBlockStatus.UnKnown then
        return
    end

    self._Control:OnGridBlockClick(self.RowIndex, self.ColIndex)
end

function XUiNonogramGridBlock:OnBtnGridBlockLongClicked()
    local screenClickPosition = XUiHelper.GetScreenClickPosition(self.PanelBlockTrans, self.UiCamera)
    self.Parent:OnClickPanelBlockWithPosition(screenClickPosition)
end

--function XUiNonogramGridBlock:OnBtnGridBlockLongClickUp()
--    
--end

function XUiNonogramGridBlock:SetStatus(status)
    if status == XEnumConst.Nonogram.NonogramGridBlockStatus.UnKnown then
        self.PanelRight.gameObject:SetActiveEx(false)
        self.PanelError.gameObject:SetActiveEx(false)
    elseif status == XEnumConst.Nonogram.NonogramGridBlockStatus.TrueStatus then
        self.PanelRight.gameObject:SetActiveEx(true)
        self.PanelError.gameObject:SetActiveEx(false)
    elseif status == XEnumConst.Nonogram.NonogramGridBlockStatus.FalseStatus then
        self.PanelRight.gameObject:SetActiveEx(false)
        self.PanelError.gameObject:SetActiveEx(true)
    end

    self.Status = status
end

function XUiNonogramGridBlock:SetTipsActive(isActive)
    self.PanelTips.gameObject:SetActiveEx(isActive)
end

function XUiNonogramGridBlock:CheckStatus(status)
    return self.Status == status
end

return XUiNonogramGridBlock