---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 11:04
---

---@class XUiNonogramPopupSettlement:XLuaUi
---@field _Control XNonogramControl
local XUiNonogramPopupSettlement = XLuaUiManager.Register(XLuaUi, "UiNonogramPopupSettlement")

function XUiNonogramPopupSettlement:OnAwake()

end

function XUiNonogramPopupSettlement:OnStart()
    self:RegisterBtnListener()
end

function XUiNonogramPopupSettlement:OnEnable(isFinished, isPassAll, sureCallBack, cancelCallBack)
    self.IsFinished = isFinished
    self.IsPassAll = isPassAll
    self.SureCallBack = sureCallBack
    self.CancelCallBack = cancelCallBack

    self:Refresh()
end

function XUiNonogramPopupSettlement:OnDisable()

end

function XUiNonogramPopupSettlement:OnDestroy()

end

function XUiNonogramPopupSettlement:RegisterBtnListener()
    self.BtnCancel.CallBack = function()
        self:Close()
        if self.CancelCallBack then
            self.CancelCallBack()
        end
    end
    self.BtnTongBlack.CallBack = function()
        if self.SureCallBack then
            self.SureCallBack()
        end
    end
    self.BtnTongBlack.IsOpenClickCD = true
    self.BtnTanchuangCloseBig.CallBack = function()
        if self.IsFinished then
            if self.SureCallBack then
                self.SureCallBack()
            end
        else
            self:Close()
            if self.CancelCallBack then
                self.CancelCallBack()
            end
        end
    end
end

function XUiNonogramPopupSettlement:Refresh()
    self.BtnCancel.gameObject:SetActiveEx(not self.IsFinished)
    local textTitle = ""
    if self.IsFinished then
        if self.IsPassAll then
            textTitle = XUiHelper.GetText("NonogramSettlementTitleAllFinish")
        else
            textTitle = XUiHelper.GetText("NonogramSettlementTitleFinish")
        end
    else
        textTitle = XUiHelper.GetText("NonogramSettlementTitleExit")
    end
    self.TxtTitle.text = textTitle
    self.TxtMapNum.text = self.IsPassAll and self._Control:GetOneGamePlayMapCount() or self._Control:GetOneGamePlayMapCount() - 1
    local unlockCGItemId = self._Control:GetUnlockCgItemId(self._Control:GetCurChapterId())
    if XTool.IsNumberValid(unlockCGItemId) then
        self.RImgIcon:SetRawImage(XDataCenter.ItemManager.GetItemIcon(unlockCGItemId))
        self.TxtNum.text = self._Control:GetOneGameUnlockCGItemCount()
        self.PanelReward.gameObject:SetActiveEx(true)
    else
        self.PanelReward.gameObject:SetActiveEx(false)
    end
end