---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/11 18:01
---

local XUiSucceedBossPanelGarrisonItem = XClass(nil, "XUiSucceedBossPanelGarrisonItem")

local State = {
    Lock = 1, -- 锁定
    NoGarrison = 2, -- 未驻守
    CanChange = 3, -- 驻守可更换
    CanNotChange = 4, -- 驻守不可更换
}

function XUiSucceedBossPanelGarrisonItem:Ctor(ui, parent)
    ---@type UnityEngine.GameObject
    self.GameObject = ui.gameObject
    ---@type UnityEngine.RectTransform
    self.Transform = ui.transform
    self.Parent = parent
    XTool.InitUiObject(self)
    
    self:InitAutoScript()

    self.State = State.Lock
end

function XUiSucceedBossPanelGarrisonItem:InitAutoScript()
    XUiHelper.RegisterClickEvent(self, self.BtnGarrison, self.OnBtnGarrisonClick)
end

function XUiSucceedBossPanelGarrisonItem:OnBtnGarrisonClick()
    if self.State == State.Lock then
        return
    end

    if self.State == State.CanNotChange then
        return
    end

    XLuaUiManager.Open("UiSucceedBossPopupChooseGarrison") -- 不需要传参数，必定驻守上一完成关卡
    --self.Parent:OpenChildUi("UiSucceedBossPopupChooseGarrison")
end

--    local garrisonInfo = {
--        IsLocked = true,
--        DefendId = 0,
--        IsRobot = false,
--        IsCanChange = false,
--    }
function XUiSucceedBossPanelGarrisonItem:Refresh(garrisonInfo)
    if not garrisonInfo then
        return
    end

    if garrisonInfo.IsLocked then
        self:SetState(State.Lock)
        return
    end

    if XTool.IsNumberValid(garrisonInfo.DefendId) then
        local characterIcon = self.Parent:GetSucceedBossCharacterBuffIconAndDesc(garrisonInfo.DefendId)
        self.RImgHead:SetRawImage(characterIcon)
        if garrisonInfo.IsCanChange then
            self:SetState(State.CanChange)
        else
            self:SetState(State.CanNotChange)
        end
    else
        self:SetState(State.NoGarrison)
    end
end

function XUiSucceedBossPanelGarrisonItem:SetState(state)
    self.State = state
    if state == State.Lock then
        --self.RImgHead.gameObject:SetActiveEx(false)
        --self.ImgLock.gameObject:SetActiveEx(true)
        self.GameObject:SetActiveEx(false)
    elseif state == State.NoGarrison then
        self.RImgHead.gameObject:SetActiveEx(false)
        self.ImgLock.gameObject:SetActiveEx(false)
    elseif state == State.CanChange then
        self.RImgHead.gameObject:SetActiveEx(true)
        self.ImgLock.gameObject:SetActiveEx(false)
        self.ImgChange.gameObject:SetActiveEx(true)
    elseif state == State.CanNotChange then
        self.RImgHead.gameObject:SetActiveEx(true)
        self.ImgLock.gameObject:SetActiveEx(false)
        self.ImgChange.gameObject:SetActiveEx(false)
    end
end

return XUiSucceedBossPanelGarrisonItem