---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/5 18:03
---

local XUiSucceedBossMonsterItem = XClass(XUiNode, "XUiSucceedBossMonsterItem")

-- 构造函数
function XUiSucceedBossMonsterItem:Ctor(ui, parent)
    self:InitAutoScript()
end

function XUiSucceedBossMonsterItem:InitAutoScript()
    self:AutoAddListener()
end

function XUiSucceedBossMonsterItem:AutoAddListener()

end

function XUiSucceedBossMonsterItem:Refresh(monsterId, bossHeadUseType, monsterLevel)
    self.MonsterId = monsterId
    self.BossHeadUseType = bossHeadUseType -- 标记是哪个界面使用的
    self.MonsterLevel = monsterLevel
    self.MonsterConfig = self._Control:GetMonsterConfig(monsterId)
    if not self.MonsterConfig then
        return
    end

    self:SetShow(true)
    self:RefreshMonsterIcon()
    self:RefreshTag()
    self:RefreshLevel()
end

function XUiSucceedBossMonsterItem:RegisterClickEvent(cb)
    XUiHelper.RegisterClickEvent(self, self.BtnGridBoss, cb)
end

function XUiSucceedBossMonsterItem:SetPanelLockActive(isActive)
    self.PanelLock.gameObject:SetActiveEx(isActive)
end

function XUiSucceedBossMonsterItem:SetPanelSelectActive(isActive)
    self.ImgSelect.gameObject:SetActiveEx(isActive)
end

function XUiSucceedBossMonsterItem:RefreshMonsterIcon()
    if self.BossHeadUseType == XEnumConst.SucceedBoss.BossHeadUseType.Main then
        self.RImgHead:SetRawImage(self.MonsterConfig.ShowIconMain)
    else
        self.RImgHead:SetRawImage(self.MonsterConfig.HeadIcon)
    end
end

function XUiSucceedBossMonsterItem:RefreshTag()
    if XTool.IsNumberValid(self.MonsterConfig.Type) then
        self.PanelTag.gameObject:SetActiveEx(true)
        if self.MonsterConfig.Type == XEnumConst.SucceedBoss.BossType.Normal then
            self.TagNormal.gameObject:SetActiveEx(true)
            self.TagBoss.gameObject:SetActiveEx(false)
            self.ImgDone1.gameObject:SetActiveEx(self._Control:CheckMonsterPass(self.MonsterId))
        elseif self.MonsterConfig.Type == XEnumConst.SucceedBoss.BossType.Boss then
            self.TagNormal.gameObject:SetActiveEx(false)
            self.TagBoss.gameObject:SetActiveEx(true)
            self.ImgDone2.gameObject:SetActiveEx(self._Control:CheckMonsterPass(self.MonsterId))
        end
    else
        self.PanelTag:SetActiveEx(false)
    end

    if self.BossHeadUseType == XEnumConst.SucceedBoss.BossHeadUseType.Chapter then
        if self.Defeat then
            self.Defeat.gameObject:SetActiveEx(self._Control:CheckMonsterPassedInCurChapter(self.MonsterId))
        end
    end
end

function XUiSucceedBossMonsterItem:SetShow(isShow)
    self.PanelNone.gameObject:SetActiveEx(not isShow)
    self.PanelShow.gameObject:SetActiveEx(isShow)
end

function XUiSucceedBossMonsterItem:RefreshLevel()
    if not XTool.IsNumberValid(self.MonsterLevel) then
        self.ListDot.gameObject:SetActiveEx(false)
        return
    end

    self.ListDot.gameObject:SetActiveEx(true)
    XUiHelper.RefreshCustomizedList(self.ListDot, self.ImgDot.transform, self.MonsterLevel, function(index, go)
    end)
end

return XUiSucceedBossMonsterItem