---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/13 12:14
---

---@field _Control XSucceedBossControl

local XUiSucceedBossPopupGarrisonItem = XClass(XUiNode, "XUiSucceedBossPopupGarrisonItem")

function XUiSucceedBossPopupGarrisonItem:Ctor()
    self:InitAutoScript()
end

function XUiSucceedBossPopupGarrisonItem:InitAutoScript()
    self:InitBtnListener()
end

function XUiSucceedBossPopupGarrisonItem:InitBtnListener()
    XUiHelper.RegisterClickEvent(self, self.BtnGrid, self.OnBtnGridClick)
end

function XUiSucceedBossPopupGarrisonItem:OnBtnGridClick()
    if self.IsCanSelect then
        --self.ImgSelect.gameObject:SetActiveEx(not self.ImgSelect.gameObject.activeSelf)
        self.Parent:OnGarrisonItemClick(self.Index, self.EntityId)
    end
end

function XUiSucceedBossPopupGarrisonItem:Refresh(index, entityId, isCanSelect, isCurrent)
    self.Index = index
    self.EntityId = entityId
    self.IsCanSelect = isCanSelect
    self.IsCurrent = isCurrent
    self:RefreshUi()
end

function XUiSucceedBossPopupGarrisonItem:RefreshUi()
    local characterIcon, careerIcon, desc, fightEventName = self._Control:GetSucceedBossCharacterBuffIconAndDesc(self.EntityId)
    self.RImgHead:SetRawImage(characterIcon)
    self.RImgType:SetRawImage(careerIcon)
    self.TxtDetail.text = string.gsub(desc, "\\n", "\n")
    self.TxtFightEventName.text = fightEventName
    self.PanelCur.gameObject:SetActiveEx(self.IsCurrent)

    self:RefreshState(self.IsCurrent)
end

function XUiSucceedBossPopupGarrisonItem:RefreshState(isCurSelect)
    self.IsCurrent = isCurSelect
    if self.IsCanSelect then
        self.BtnGrid:SetButtonState(CS.UiButtonState.Normal)
        if self.IsCurrent then
            self.ImgSelected.gameObject:SetActiveEx(true)
        else
            self.ImgSelected.gameObject:SetActiveEx(false)
        end
    else
        self.BtnGrid:SetButtonState(CS.UiButtonState.Disable)
    end
end

return XUiSucceedBossPopupGarrisonItem