local XDynamicTableNormal = require("XUi/XUiCommon/XUiDynamicTable/XDynamicTableNormal")
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/4 9:58
---
local TableInsert = table.insert

local XUiSucceedBossPopupChooseWeaknessItem = require("XUi/XUiSucceedBoss/XUiSucceedBossPopupChooseWeaknessItem")
local XUiSucceedBossPopupChooseWeakness = XLuaUiManager.Register(XLuaUi, "UiSucceedBossPopupChooseWeakness")

--重写父类方法
function XUiSucceedBossPopupChooseWeakness:OnAwake()
    self._IsShowFight = false
end

function XUiSucceedBossPopupChooseWeakness:OnStart()
    self:InitAutoScript()
    self:InitData()
    
    XUiHelper.RegisterClickEvent(self, self.BtnBattle, self.OnBtnClickFight)
    XUiHelper.RegisterClickEvent(self, self.BtnBack, self.Close)
end

function XUiSucceedBossPopupChooseWeakness:OnEnable(isShowFight)
    self._IsShowFight = isShowFight
    self.CurWeaknessId = self._Control:GetElementId()
    self:Refresh()
end

function XUiSucceedBossPopupChooseWeakness:InitAutoScript()
    self:AutoAddListener()
    self.DynamicTable = XDynamicTableNormal.New(self.ListWeakness)
    self.DynamicTable:SetProxy(XUiSucceedBossPopupChooseWeaknessItem, self)
    self.DynamicTable:SetDelegate(self)
end

function XUiSucceedBossPopupChooseWeakness:AutoAddListener()
    self:RegisterClickEvent(self.BtnTanchuangClose, self.OnBtnCloseClick)
    self:RegisterClickEvent(self.BtnConfirm, self.OnBtnConfirmClick)
    self:RegisterClickEvent(self.BtnBattle, self.OnBtnClickFight)
end

function XUiSucceedBossPopupChooseWeakness:OnBtnCloseClick()
    self:Close()
end

function XUiSucceedBossPopupChooseWeakness:OnBtnConfirmClick()
    self._Control:RequestSucceedBossSelectElement(self.CurWeaknessId, function()
        self:Close()
    end)
end

function XUiSucceedBossPopupChooseWeakness:InitData()
    self.AllWeekNessList = {}
    self.AllWeekNessList = self._Control:GetSucceedBossElements()
    self.WeaknessItems = {}
end

function XUiSucceedBossPopupChooseWeakness:Refresh()
    self.AllFightEventShowConfig = self._Control:GetAllFightEventShowConfig()
    self.DynamicTable:SetDataSource(self.AllWeekNessList)
    self.DynamicTable:ReloadDataSync()
    self:RefreshBtnBattle()
end

function XUiSucceedBossPopupChooseWeakness:RefreshBtnBattle()
    if self._IsShowFight then
        self.BtnBattle.gameObject:SetActiveEx(true)
        if self.CurWeaknessId and self.CurWeaknessId > 0 then
            self.BtnBattle:SetButtonState(CS.UiButtonState.Normal)
        else
            self.BtnBattle:SetButtonState(CS.UiButtonState.Disable)
        end
        self.BtnConfirm.gameObject:SetActiveEx(false)
    else
        self.BtnBattle.gameObject:SetActiveEx(false)
        self.BtnConfirm.gameObject:SetActiveEx(true)
    end    
end

function XUiSucceedBossPopupChooseWeakness:OnDynamicTableEvent(event, index, grid)
    if event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_INIT then
        grid:Open()
        TableInsert(self.WeaknessItems, grid)
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_ATINDEX then
        grid:Refresh(self.AllWeekNessList[index], self.CurWeaknessId)
    elseif event == DYNAMIC_DELEGATE_EVENT.DYNAMIC_GRID_TOUCHED then
        self:OnSelectFightEvent(index)
    end
end

function XUiSucceedBossPopupChooseWeakness:OnSelectFightEvent(index)
    local fightEventData = self.AllWeekNessList[index]
    if not fightEventData then
        return
    end

    if self.CurWeaknessId == fightEventData.Id then
        return
    end

    self.CurWeaknessId = fightEventData.Id

    if self._IsShowFight then
        self._Control:RequestSucceedBossSelectElement(self.CurWeaknessId)
        self:RefreshBtnBattle()
    end

    for _, grid in ipairs(self.WeaknessItems) do
        grid:OnSelectEventIdChanged(self.CurWeaknessId)
    end
end

function XUiSucceedBossPopupChooseWeakness:OnBtnClickFight()
    if not self.CurWeaknessId then
        XUiManager.TipText("SucceedBossElementNotSelect")
        return
    end
    self:Close()
    XEventManager.DispatchEvent(XEventId.EVENT_SUCCEED_BOSS_CLICK_FIGHT)
end

return XUiSucceedBossPopupChooseWeakness