---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/4 9:58
---

local TableInsert = table.insert
local XUiSucceedBossPopupGarrisonItem = require("XUi/XUiSucceedBoss/XUiSucceedBossPopupGarrisonItem")
local XUiSucceedBossPopupChooseGarrison = XLuaUiManager.Register(XLuaUi, "UiSucceedBossPopupChooseGarrison")

--重写父类方法
function XUiSucceedBossPopupChooseGarrison:OnAwake()

end

function XUiSucceedBossPopupChooseGarrison:OnStart()
    self.GarrisonItems = {}
    self:InitAutoScript()
end

function XUiSucceedBossPopupChooseGarrison:OnEnable()
    self:InitData()
    self:Refresh()
end

function XUiSucceedBossPopupChooseGarrison:InitAutoScript()
    self:RegisterBtnEvent()
end

function XUiSucceedBossPopupChooseGarrison:RegisterBtnEvent()
    self:RegisterClickEvent(self.BtnConfirm, self.OnBtnConfirmClick)
    self:RegisterClickEvent(self.BtnTanchuangClose, self.OnBtnTanchuangCloseClick)
end

function XUiSucceedBossPopupChooseGarrison:OnBtnTanchuangCloseClick()
    self:Close()
end

function XUiSucceedBossPopupChooseGarrison:OnBtnConfirmClick()
    if not XTool.IsNumberValid(self.CurSelectEntityId) then
        XUiManager.TipText("SucceedBossChooseGarrison")
        return
    end

    self._Control:RequestSucceedBossSetDefendCharacter(self.CurSelectEntityId, function()
        self:Close()
    end)
end

function XUiSucceedBossPopupChooseGarrison:InitData()
    self.CurSelectEntityId = self._Control:GetCurGarrisonId()
end

function XUiSucceedBossPopupChooseGarrison:Refresh()
    local characterIds = {}
    for _, entityId in pairs(self._Control:GetTeam():GetEntityIds()) do
        if (XTool.IsNumberValid(entityId)) then
            TableInsert(characterIds, entityId)
        end
    end
    local unalterableGarrisonIds = self._Control:GetUnalterableGarrisonIds()
    local curGarrisonId = self._Control:GetCurGarrisonId()

    local index = 1
    if XTool.IsNumberValid(curGarrisonId) then
        self:RefreshGarrisonItems(index, { curGarrisonId }, true, true)
        index = index + 1
    end
    self:RefreshGarrisonItems(index, characterIds, true, false)
    index = index + XTool.GetTableCount(characterIds)
    self:RefreshGarrisonItems(index, unalterableGarrisonIds, false, false)
end

function XUiSucceedBossPopupChooseGarrison:RefreshGarrisonItems(startIndex, data, isCanSelect, isCurrent)
    for i = 1, XTool.GetTableCount(data) do
        local index = startIndex + i - 1
        local gridGarrisonItem = self.GarrisonItems[index]
        if gridGarrisonItem == nil then
            local tempGameObject = XUiHelper.Instantiate(self.GridCharacter, self.ListCharacter)
            gridGarrisonItem = XUiSucceedBossPopupGarrisonItem.New(tempGameObject, self)
            self.GarrisonItems[index] = gridGarrisonItem
        end

        gridGarrisonItem:Open()
        gridGarrisonItem:Refresh(index, data[i], isCanSelect, isCurrent)
    end
end

function XUiSucceedBossPopupChooseGarrison:OnGarrisonItemClick(index, entityId)
    if self.CurSelectEntityId == entityId then
        return
    end

    for i, item in pairs(self.GarrisonItems) do
        item:RefreshState(index == i)
    end
    self.CurSelectEntityId = entityId
end

return XUiSucceedBossPopupChooseGarrison