---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/7 14:56
---

local XUiSucceedBossPopupSkillGridItem = XClass(nil, "XUiSucceedBossPopupSkillGridItem")

function XUiSucceedBossPopupSkillGridItem:Ctor(ui, control)
    self._Control = control
    XUiHelper.InitUiClass(self, ui)
end

function XUiSucceedBossPopupSkillGridItem:Refresh(fightEventId)
    if XTool.IsNumberValid(fightEventId) then
        local fightEventConfig = self._Control:GetFightEventShowConfig(fightEventId)
        if fightEventConfig then
            self.RImgIcon:SetRawImage(fightEventConfig.Icon)
            self.TxtName.text = fightEventConfig.Name
            local desc = fightEventConfig.Desc
            self.TxtDetail.text = string.gsub(desc, "\\n", "\n")
        end
    end
end

return XUiSucceedBossPopupSkillGridItem