---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/17 11:30
---
local XUiSucceedBossMonsterItem = require("XUi/XUiSucceedBoss/XSucceedBossMonsterItem")

local XUiSucceedBossSettlementTeamItem = XClass(XUiNode, "XUiSucceedBossSettlementTeamItem")

function XUiSucceedBossSettlementTeamItem:Refresh(data)
    local teamEntityIds = self:GetTeamEntityIds(data)
    self:RefreshTeam(teamEntityIds)
    self:RefreshGridBoss(data)
    self:RefreshFightTime(data)
    self:RefreshScore(data)
end

function XUiSucceedBossSettlementTeamItem:GetTeamEntityIds(data)
    local teamEntityIds = {}
    for _, characterResult in ipairs(data.CharacterResultList) do
        table.insert(teamEntityIds, characterResult.CharacterId)
    end

    return teamEntityIds
end

function XUiSucceedBossSettlementTeamItem:RefreshTeam(entityIds)
    XUiHelper.RefreshCustomizedList(self.ListCharacter, self.GridHead, #entityIds, function(index, go)
        local entityId = entityIds[index]
        local icon = self._Control:GetSucceedBossCharacterBuffIconAndDesc(entityId)
        go.transform:Find("RImgHead"):GetComponent("RawImage"):SetRawImage(icon)
    end)
end

function XUiSucceedBossSettlementTeamItem:RefreshGridBoss(data)
    local monsterId = data.MonsterId
    local monsterGridItem = XUiSucceedBossMonsterItem.New(self.GridBoss, self)
    monsterGridItem:Open()
    monsterGridItem:Refresh(monsterId, false)
end

function XUiSucceedBossSettlementTeamItem:RefreshFightTime(data)
    local isSweep = data.IsSweep
    local fightTime = data.FightTime
    if isSweep then
        self.TxtAuto.gameObject:SetActiveEx(true)
        self.TxtTime.gameObject:SetActiveEx(false)
        self.TxtTitle.gameObject:SetActiveEx(false)
    else
        self.TxtAuto.gameObject:SetActiveEx(false)
        self.TxtTime.gameObject:SetActiveEx(true)
        self.TxtTitle.gameObject:SetActiveEx(true)
        self.TxtTime.text = XUiHelper.GetTime(fightTime)
    end
end

function XUiSucceedBossSettlementTeamItem:RefreshScore(data)
    local monsterId = data.MonsterId
    local monsterLevel = data.MonsterLevel
    local monsterLevelScore = self._Control:GetMonsterLevelScore(monsterId, monsterLevel)
    if XTool.IsNumberValid(monsterLevelScore) then
        self.PanelScore.gameObject:SetActiveEx(true)
        self.TxtScore.text = monsterLevelScore
    else
        self.PanelScore.gameObject:SetActiveEx(false)
    end
end

function XUiSucceedBossSettlementTeamItem:PlayGridTeamEnableAnimation()
    if self.GridTeamEnable then
        self.GridTeamEnable:PlayTimelineAnimation()
    end
end

return XUiSucceedBossSettlementTeamItem