---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/4 9:58
---

local XUiSucceedBossPopupGarrisonDetailItem = require("XUi/XUiSucceedBoss/XUiSucceedBossPopupGarrisonDetailItem")
local XUiSucceedBossPopupGarrisonDetail = XLuaUiManager.Register(XLuaUi, "UiSucceedBossPopupGarrisonDetail")

--重写父类方法
function XUiSucceedBossPopupGarrisonDetail:OnAwake()

end

function XUiSucceedBossPopupGarrisonDetail:OnStart()
    self:InitData()
    self:AutoRegisterBtnListener()
    self:Refresh()
end

function XUiSucceedBossPopupGarrisonDetail:InitData()
    self.GarrisonDetailItems = {}
end

function XUiSucceedBossPopupGarrisonDetail:AutoRegisterBtnListener()
    self:RegisterClickEvent(self.BtnTanchuangClose, self.OnBtnCloseClick)
end

function XUiSucceedBossPopupGarrisonDetail:OnBtnCloseClick()
    self:Close()
end

function XUiSucceedBossPopupGarrisonDetail:Refresh()
    local garrisonFightEventIdList, fightEventIdToCharIcon = self._Control:GetGarrisonFightEventIds()

    XUiHelper.RefreshCustomizedList(self.ListGarrison, self.GridGarrison, #garrisonFightEventIdList, function(index, go)
        local item = XUiSucceedBossPopupGarrisonDetailItem.New(go, self)
        local fightEventId = garrisonFightEventIdList[index]
        local fightEventShowConfig = self._Control:GetFightEventShowConfig(fightEventId)
        item:Refresh(fightEventIdToCharIcon[fightEventId], fightEventShowConfig.Icon, fightEventShowConfig.Desc)
    end)
end

return XUiSucceedBossPopupGarrisonDetail