---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/18 16:05
---

local XUiSucceedBossPopupGarrisonDetailItem = XClass(XUiNode, "UiSucceedBossPopupGarrisonDetailItem")

function XUiSucceedBossPopupGarrisonDetailItem:Refresh(headIconList, icon, desc)
    self.RImgType:SetRawImage(icon)
    self.TxtDetail.text = string.gsub(desc, "\\n", "\n")

    XUiHelper.RefreshCustomizedList(self.HeadList, self.RImgHeadIcon, #headIconList, function(index, go)
        go:GetComponent("RawImage"):SetRawImage(headIconList[index])
    end)
end

return XUiSucceedBossPopupGarrisonDetailItem