---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/4 9:58
---

local XUiSucceedBossChapterGridSkillItem = require("XUi/XUiSucceedBoss/XUiSucceedBossChapterGridSkillItem")
local XUiSucceedBossSettlementTeamItem = require("XUi/XUiSucceedBoss/XUiSucceedBossSettlementTeamItem")

local XUiSucceedBossSettlement = XLuaUiManager.Register(XLuaUi, "UiSucceedBossSettlement")

--重写父类方法
function XUiSucceedBossSettlement:OnAwake()

end

function XUiSucceedBossSettlement:OnStart(battleResults, chapterId)
    self:InitAutoScript()
    self:Refresh(battleResults, chapterId)
end

function XUiSucceedBossSettlement:OnEnable()

end

function XUiSucceedBossSettlement:InitAutoScript()
    self:RegisterBtnEvent()
end

function XUiSucceedBossSettlement:RegisterBtnEvent()
    self:RegisterClickEvent(self.BtnConfirm, self.OnBtnConfirmClick)
end

function XUiSucceedBossSettlement:OnBtnConfirmClick()
    XLuaUiManager.SafeClose("UiBattleRoleRoom")
    XLuaUiManager.SafeClose("UiSucceedBossChapter")
    self:Close()
end

function XUiSucceedBossSettlement:Refresh(battleResults, chapterId)
    local skillFightEventList, buffFightEventList = self:GetSkillAndBuffFightEventList(battleResults)
    self:RefreshChapterName(chapterId)
    self:RefreshSkill(skillFightEventList)
    self:RefreshBuff(buffFightEventList)
    self:RefreshTeams(battleResults)
    self:RefreshScore(battleResults)
end

function XUiSucceedBossSettlement:RefreshTeams(battleResults)
    XUiHelper.RefreshCustomizedList(self.ListTeam, self.GridTeam, #battleResults, function(index, go)
        local teamItem = XUiSucceedBossSettlementTeamItem.New(go, self)
        teamItem:Refresh(battleResults[index])
        local animationDelay = index * 0.3
        self:Tween(animationDelay, function()
        end, function()
            teamItem:PlayGridTeamEnableAnimation()
        end)
    end)
end

function XUiSucceedBossSettlement:GetSkillAndBuffFightEventList(battleResults)
    local skillFightEventList = {}
    local buffFightEventList = {}
    for _, battleResult in ipairs(battleResults) do
        local monsterId = battleResult.MonsterId
        if XTool.IsNumberValid(monsterId) then
            local monsterStageConfig = self._Control:GetMonsterConfig(monsterId)
            if monsterStageConfig then
                local skillFightEventId = monsterStageConfig.SkillFightEventId
                if XTool.IsNumberValid(skillFightEventId) then
                    table.insert(skillFightEventList, skillFightEventId)
                end
                local buffFightEventId = monsterStageConfig.BuffFightEventId
                if XTool.IsNumberValid(buffFightEventId) then
                    table.insert(buffFightEventList, buffFightEventId)
                end
            end
        end
    end
    return skillFightEventList, buffFightEventList
end

function XUiSucceedBossSettlement:RefreshChapterName(chapterId)
    if not XTool.IsNumberValid(chapterId) then
        return
    end
    local chapterConfig = self._Control:GetChapterConfig(chapterId)
    self.TxtTitle.text = chapterConfig.Name
end

function XUiSucceedBossSettlement:RefreshSkill(skillFightEventList)
    XUiHelper.RefreshCustomizedList(self.ListSkill, self.GridSkill, #skillFightEventList, function(index, go)
        local gridSkillItem = XUiSucceedBossChapterGridSkillItem.New(go, self)
        gridSkillItem:Refresh(skillFightEventList[index], true, false, true)
    end)
end

function XUiSucceedBossSettlement:RefreshBuff(buffFightEventList)
    XUiHelper.RefreshCustomizedList(self.ListBuff, self.GridBuff, #buffFightEventList, function(index, go)
        local gridBuffItem = XUiSucceedBossChapterGridSkillItem.New(go, self)
        gridBuffItem:Refresh(buffFightEventList[index], false, false, true)
    end)
end

function XUiSucceedBossSettlement:RefreshScore(battleResults)
    local totalScore = 0

    for _, battleResult in pairs(battleResults) do
        local monsterLevelScore = self._Control:GetMonsterLevelScore(battleResult.MonsterId, battleResult.MonsterLevel)
        totalScore = totalScore + monsterLevelScore
    end

    if XTool.IsNumberValid(totalScore) then
        self.TxtScore.text = totalScore
    else
        self.TxtScore.gameObject:SetActiveEx(false)
    end
end

return XUiSucceedBossSettlement