---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/7 18:59
---

local XUiSucceedBossPopupChooseWeaknessItem = XClass(XUiNode, "XUiSucceedBossPopupChooseWeaknessItem")

--function XUiSucceedBossPopupChooseWeaknessItem:Init(go, parent)
--    self.GameObject = go
--    self.Transform = go.transform
--    self.Parent = parent
--    XTool.InitUiObject(self)
--end

function XUiSucceedBossPopupChooseWeaknessItem:Refresh(weaknessData, curWeaknessId)
    self.WeaknessData = weaknessData
    self.RImgType:SetRawImage(weaknessData.Icon)
    self.TxtName.text = weaknessData.Name
    local desc = weaknessData.Desc
    self.TxtDetail.text = string.gsub(desc, "\\n", "\n")
    self:OnSelectEventIdChanged(curWeaknessId)
end

function XUiSucceedBossPopupChooseWeaknessItem:SetSelect(isSelect)
    if isSelect then
        self.ImgSelect.gameObject:SetActiveEx(true)
    else
        self.ImgSelect.gameObject:SetActiveEx(false)
    end
end

function XUiSucceedBossPopupChooseWeaknessItem:OnSelectEventIdChanged(curWeaknessId)
    if XTool.IsNumberValid(curWeaknessId) and curWeaknessId == self.WeaknessData.Id then
        self:SetSelect(true)
    else
        self:SetSelect(false)
    end
end

return XUiSucceedBossPopupChooseWeaknessItem