---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/6 16:54
---

local XUiSucceedBossChapterGridSkillItem = XClass(nil, "XUiSucceedBossChapterGridSkillItem")

function XUiSucceedBossChapterGridSkillItem:Ctor(ui, parent)
    self.GameObject = ui.gameObject
    self.Transform = ui.transform
    self.Parent = parent
    self._Control = parent._Control
    XTool.InitUiObject(self)

    self:InitAutoScript()

    if self.TagNew then
        self.TagNew.gameObject:SetActiveEx(false)
    end
end

function XUiSucceedBossChapterGridSkillItem:InitAutoScript()
    self:AutoAddListener()
end

function XUiSucceedBossChapterGridSkillItem:AutoAddListener()
    XUiHelper.RegisterClickEvent(self, self.BtnGrid, self.OnBtnGridClick)
end

function XUiSucceedBossChapterGridSkillItem:OnBtnGridClick()
    if self.IsNotNeedClick then
        return
    end
    local selectIndex = self.Parent.ChapterConfig.Type == XEnumConst.SucceedBoss.ChapterType.Optional and self.Parent.SelectIndex or nil
    self.Parent:OpenChildUi("UiSucceedBossPopupSkill", self.IsSkill, selectIndex)
end

function XUiSucceedBossChapterGridSkillItem:Refresh(fightEventId, isSkill, isNew, isNotNeedClick)
    self.IsSkill = isSkill
    self.IsNotNeedClick = isNotNeedClick
    if XTool.IsNumberValid(fightEventId) then
        local icon = self._Control:GetFightEventIcon(fightEventId)
        self.RImgIcon:SetRawImage(icon)
        if self.TagNew then
            self.TagNew.gameObject:SetActiveEx(isNew)
        end
    end
end

return XUiSucceedBossChapterGridSkillItem