---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/23 15:42
---
local XRedPointConditionNonogramMain = {}

function XRedPointConditionNonogramMain.Check()
    return XMVCA.XNonogram:CheckActivityPoint()
end

return XRedPointConditionNonogramMain