---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/10 15:03
---

local Events = nil
local XRedPointConditionSucceedBossChapter = {}

function XRedPointConditionSucceedBossChapter.GetSubEvents()
    Events = Events or {
        XRedPointEventElement.New(XEventId.EVENT_NONOGRAM_CHAPTER_UNLOCK),
        XRedPointEventElement.New(XEventId.EVENT_NONOGRAM_CHAPTER_REWARDED),
        XRedPointEventElement.New(XEventId.EVENT_NONOGRAM_GAME_CHAPTER_START),
    }
    return Events
end

function XRedPointConditionSucceedBossChapter.Check(chapterId)
    return XMVCA.XNonogram:CheckChapterPoint(chapterId)
end

return XRedPointConditionSucceedBossChapter