---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/23 15:42
---
local Events = nil
local XRedPointConditionSucceedBossTaskTab = {}

function XRedPointConditionSucceedBossTaskTab.GetSubEvents()
    Events = Events or {
        XRedPointEventElement.New(XEventId.EVENT_FINISH_TASK),
        XRedPointEventElement.New(XEventId.EVENT_TASK_SYNC),
    }
    return Events
end

function XRedPointConditionSucceedBossTaskTab.Check(tabIndex)
    return XMVCA.XSucceedBoss:CheckTaskTabRedPoint(tabIndex)
end

return XRedPointConditionSucceedBossTaskTab