---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/23 15:42
---
local Events = nil
local XRedPointConditionSucceedBossChapter = {}

function XRedPointConditionSucceedBossChapter.GetSubEvents()
    Events = Events or {
        XRedPointEventElement.New(XEventId.EVENT_SUCCEED_BOSS_SELECT_CHAPTER),
    }
    return Events
end

function XRedPointConditionSucceedBossChapter.Check(chapterId)
    return XMVCA.XSucceedBoss:CheckChapterRedPoint(chapterId)
end

return XRedPointConditionSucceedBossChapter