---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/23 15:42
---
local XRedPointConditionSucceedBoss = {}

function XRedPointConditionSucceedBoss.Check()
    return XMVCA.XSucceedBoss:ExCheckIsShowRedPoint()
end

return XRedPointConditionSucceedBoss