XConfigCenter = XConfigCenter or {}

local IsWindowsEditor = XMain.IsWindowsEditor
local ConfigCenterProfiler = nil
 
local function InitConfig(config, key) 
    if IsWindowsEditor then
        local profiler = ConfigCenterProfiler:CreateChild(key)
        profiler:Start()
        -- XPerformance.RecordLuaMemData(key, function()
        config.Init()
        -- end)
        profiler:Stop()
    else
        config.Init()
    end
end

function XConfigCenter.Init()
    ConfigCenterProfiler = XGame.Profiler:CreateChild("XConfigCenter")
    ConfigCenterProfiler:Start()
    
    InitConfig(XDlcConfig,"XDlcConfig")
    
    -- 新拆分出的Config
    InitConfig(XAssistConfig, "XAssistConfig")
    InitConfig(XAutoFightConfig, "XAutoFightConfig")
    InitConfig(XFubenBossOnlineConfig, "XFubenBossOnlineConfig")
    InitConfig(XFubenUrgentEventConfig, "XFubenUrgentEventConfig")
    InitConfig(XLoadingConfig, "XLoadingConfig")
    InitConfig(XTeamConfig, "XTeamConfig")
    InitConfig(XFunctionConfig, "XFunctionConfig")

    InitConfig(XAttribConfigs, "XAttribConfigs")
    InitConfig(XUiConfigs, "XUiConfigs")
    InitConfig(XGuideConfig, "XGuideConfig")
    InitConfig(XItemConfigs, "XItemConfigs")
    InitConfig(XCharacterConfigs, "XCharacterConfigs")
    InitConfig(XSignBoardConfigs, "XSignBoardConfigs")
    InitConfig(XEquipConfig, "XEquipConfig")
    InitConfig(XComeAcrossConfig, "XComeAcrossConfig")
    InitConfig(XFavorabilityConfigs, "XFavorabilityConfigs")
    InitConfig(XArenaConfigs, "XArenaConfigs")
    InitConfig(XArenaOnlineConfigs, "XArenaOnlineConfigs")
    InitConfig(XTrialConfigs, "XTrialConfigs")
    InitConfig(XCommunicationConfig, "XCommunicationConfig")
    InitConfig(XPrequelConfigs, "XPrequelConfigs")
    InitConfig(XTaskConfig, "XTaskConfig")
    InitConfig(XFubenConfigs, "XFubenConfigs")
    InitConfig(XTaskForceConfigs, "XTaskForceConfigs")
    InitConfig(XDrawConfigs, "XDrawConfigs")
    InitConfig(XGachaConfigs, "XGachaConfigs")
    InitConfig(XFubenMainLineConfigs, "XFubenMainLineConfigs")
    InitConfig(XFubenBossSingleConfigs, "XFubenBossSingleConfigs")
    InitConfig(XFubenExperimentConfigs, "XFubenExperimentConfigs")
    InitConfig(XMailConfigs, "XMailConfigs")
    InitConfig(XBfrtConfigs, "XBfrtConfigs")
    InitConfig(XBountyTaskConfigs, "XBountyTaskConfigs")
    InitConfig(XHostelConfigs, "XHostelConfigs")
    InitConfig(XBaseEquipConfigs, "XBaseEquipConfigs")
    InitConfig(XFurnitureConfigs, "XFurnitureConfigs")
    InitConfig(XPayConfigs, "XPayConfigs")
    InitConfig(XFubenExploreConfigs, "XFubenExploreConfigs")
    InitConfig(XFubenActivityBranchConfigs, "XFubenActivityBranchConfigs")
    InitConfig(XFubenActivityBossSingleConfigs, "XFubenActivityBossSingleConfigs")
    InitConfig(XFubenRepeatChallengeConfigs, "XFubenRepeatChallengeConfigs")
    InitConfig(XDormConfig, "XDormConfig")
    InitConfig(XMovieConfigs, "XMovieConfigs")
    InitConfig(XExhibitionConfigs, "XExhibitionConfigs")
    InitConfig(XAutoWindowConfigs, "XAutoWindowConfigs")
    InitConfig(XPlayerInfoConfigs, "XPlayerInfoConfigs")
    InitConfig(XSignInConfigs, "XSignInConfigs")
    InitConfig(XReportConfigs, "XReportConfigs")

    InitConfig(XPracticeConfigs, "XPracticeConfigs")
    InitConfig(XFubenUnionKillConfigs, "XFubenUnionKillConfigs")
    InitConfig(XFubenSpecialTrainConfig, "XFubenSpecialTrainConfig")
    InitConfig(XShopConfigs, "XShopConfigs")
    InitConfig(XHelpCourseConfig, "XHelpCourseConfig")
    InitConfig(XMedalConfigs, "XMedalConfigs")
    InitConfig(XArchiveConfigs, "XArchiveConfigs")
    InitConfig(XGuildConfig, "XGuildConfig")
    InitConfig(XFestivalActivityConfig, "XFestivalActivityConfig")
    InitConfig(XFubenBabelTowerConfigs, "XFubenBabelTowerConfigs")
    InitConfig(XFubenRogueLikeConfig, "XFubenRogueLikeConfig")
    InitConfig(XMarketingActivityConfigs, "XMarketingActivityConfigs")
    InitConfig(XFubenAssignConfigs, "XFubenAssignConfigs")
    InitConfig(XRegressionConfigs, "XRegressionConfigs")
    InitConfig(XPlatformShareConfigs, "XPlatformShareConfigs")
    InitConfig(XRewardConfigs, "XRewardConfigs")
    InitConfig(XMusicPlayerConfigs, "XMusicPlayerConfigs")
    InitConfig(XFubenExtraChapterConfigs, "XFubenExtraChapterConfigs")
    InitConfig(XDailyDungeonConfigs, "XDailyDungeonConfigs")
    InitConfig(XCharacterUiEffectConfig, "XCharacterUiEffectConfig")
    InitConfig(XHeadPortraitConfigs, "XHeadPortraitConfigs")
    InitConfig(XGuildBossConfig, "XGuildBossConfig")
    InitConfig(XEliminateGameConfig, "XEliminateGameConfig")
    InitConfig(XWorldBossConfigs, "XWorldBossConfigs")
    InitConfig(XMaintainerActionConfigs, "XMaintainerActionConfigs")

    InitConfig(XExpeditionConfig, "XExpeditionConfig")
    InitConfig(XRpgTowerConfig, "XRpgTowerConfig")
    InitConfig(XClickClearGameConfigs, "XClickClearGameConfigs")
    InitConfig(XFubenZhouMuConfigs, "XFubenZhouMuConfigs")
    InitConfig(XNieRConfigs, "XNieRConfigs")
    InitConfig(XMentorSystemConfigs, "XMentorSystemConfigs")
    InitConfig(XCollectionWallConfigs, "XCollectionWallConfigs")
    InitConfig(XActivityConfigs, "XActivityConfigs")
    InitConfig(XPurchaseConfigs, "XPurchaseConfigs")
    InitConfig(XActivityBriefConfigs, "XActivityBriefConfigs")
    InitConfig(XSetConfigs, "XSetConfigs")
    InitConfig(XRedEnvelopeConfigs, "XRedEnvelopeConfigs")
    InitConfig(XVideoConfig, "XVideoConfig")
    InitConfig(XWeaponFashionConfigs, "XWeaponFashionConfigs")
    InitConfig(XFubenInfestorExploreConfigs, "XFubenInfestorExploreConfigs")
    InitConfig(XPuzzleActivityConfigs, "XPuzzleActivityConfigs")
    InitConfig(XChatConfigs, "XChatConfigs")
    InitConfig(XPhotographConfigs, "XPhotographConfigs")
    InitConfig(XTRPGConfigs, "XTRPGConfigs")
    InitConfig(XPokemonConfigs, "XPokemonConfigs")
    InitConfig(XSpringFestivalActivityConfigs, "XSpringFestivalActivityConfigs")
    InitConfig(XFubenActivityPuzzleConfigs, "XFubenActivityPuzzleConfigs")
    InitConfig(XFubenNewCharConfig, "XFubenNewCharConfig")
    InitConfig(XSceneModelConfigs, "XSceneModelConfigs")
    InitConfig(XRoomCharFilterTipsConfigs, "XRoomCharFilterTipsConfigs")
    InitConfig(XChessPursuitConfig, "XChessPursuitConfig")
    InitConfig(XComposeGameConfig, "XComposeGameConfig")
    InitConfig(XLottoConfigs, "XLottoConfigs")
    InitConfig(XPartnerConfigs, "XPartnerConfigs")
    InitConfig(XWhiteValentineConfig, "XWhiteValentineConfig")
    InitConfig(XSpecialShopConfigs, "XSpecialShopConfigs")
    InitConfig(XFashionConfigs, "XFashionConfigs")
    InitConfig(XFingerGuessingConfig, "XFingerGuessingConfig")
    InitConfig(XReformConfigs, "XReformConfigs")
    InitConfig(XPartnerTeachingConfigs, "XPartnerTeachingConfigs")
    InitConfig(XScratchTicketConfig, "XScratchTicketConfig")
    InitConfig(XRpgMakerGameConfigs, "XRpgMakerGameConfigs")
    InitConfig(XInvertCardGameConfig, "XInvertCardGameConfig")
    InitConfig(XMineSweepingConfigs, "XMineSweepingConfigs")
    InitConfig(XSuperTowerConfigs, "XSuperTowerConfigs")
    InitConfig(XFashionStoryConfigs, "XFashionStoryConfigs")
    InitConfig(XPassportConfigs, "XPassportConfigs")
    InitConfig(XGuardCampConfig, "XGuardCampConfig")
    InitConfig(XFubenSimulatedCombatConfig, "XFubenSimulatedCombatConfig")
    InitConfig(XChristmasTreeConfig, "XChristmasTreeConfig")
    InitConfig(XCoupletGameConfigs, "XCoupletGameConfigs")
    InitConfig(XStrongholdConfigs, "XStrongholdConfigs")
    InitConfig(XMoeWarConfig, "XMoeWarConfig")
    InitConfig(XMovieAssembleConfig, "XMovieAssembleConfig")
    InitConfig(XFubenHackConfig, "XFubenHackConfig")
    InitConfig(XFubenCoupleCombatConfig, "XFubenCoupleCombatConfig")
    InitConfig(XPokerGuessingConfig, "XPokerGuessingConfig")
    InitConfig(XKillZoneConfigs, "XKillZoneConfigs")
    InitConfig(XSlotMachineConfigs, "XSlotMachineConfigs")
    InitConfig(XReformConfigs, "XReformConfigs");
    InitConfig(XPartnerTeachingConfigs, "XPartnerTeachingConfigs");
    InitConfig(XScratchTicketConfig, "XScratchTicketConfig");
    InitConfig(XRpgMakerGameConfigs, "XRpgMakerGameConfigs");
    InitConfig(XInvertCardGameConfig, "XInvertCardGameConfig");
    InitConfig(XUiPcConfig, "XUiPcConfig");

    XGuardCampConfig.Init()
    XFubenSimulatedCombatConfig.Init()
    XChristmasTreeConfig.Init()
    XCoupletGameConfigs.Init()
    XStrongholdConfigs.Init()
    XMoeWarConfig.Init()
    XMovieAssembleConfig.Init()
    XFubenHackConfig.Init()
    XFubenCoupleCombatConfig.Init()
    XPokerGuessingConfig.Init()
    XSlotMachineConfigs.Init()

    ConfigCenterProfiler:Stop()
end