---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/7/15 15:04
---
local this = XLuaUiManager.Register(XLuaUi, "UiLoginDialog")
local SwitchPanel = require("XUi/XUiLogin/XLoginSwitchAccountPanel")
local AttentionPanel = require("XUi/XUiLogin/XLoginAttentionPanel")
local NoticePanel = require("XUi/XUiLogin/XLoginNoticePanel")

function this:OnAwake()
    SwitchPanel.OnAwake(self.PanelAccountSwich.gameObject)
    AttentionPanel.OnAwake(self.PanelAttention.gameObject)
    NoticePanel.OnAwake(self.PanelMenu.gameObject)
end

function this:OnStart(panelType)
    self.PanelAccountSwich.gameObject:SetActiveEx(panelType == "Account")
    self.PanelAttention.gameObject:SetActiveEx(panelType == "Tip")
    self.PanelMenu.gameObject:SetActiveEx(panelType == "Menu")
    XEventManager.RemoveEventListener(XEventId.EVENT_LOGIN_ATTENTION, self.OpenAttention, self)
    XEventManager.AddEventListener(XEventId.EVENT_LOGIN_ATTENTION, self.OpenAttention, self)
end

function this:OpenAttention(callback)
    AttentionPanel.Open(callback)
end
