---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/7/23 17:18
---

local this = XLuaUiManager.Register(XLuaUi, "UiAccountSign")

local LookStatus = {
    Clear = 1,
    Pass = 2,
    Switch = 3
}

function this:OnAwake()
    XTool.InitUiObject(self)
    XUiHelper.RegisterClickEvent(self, self.BtnTanchuangClose, self.OnCloseLogin)
    XUiHelper.RegisterClickEvent(self, self.BtnLook, self.OnLookPassword)
    XUiHelper.RegisterClickEvent(self, self.BtnConfirm, self.OnLogin)
end

function this:OnStart(loginCallback, cancelCallback)
    self.LookStatus = LookStatus.Pass;
    self.InFPassword.text = ""
    self.ImgLook.gameObject:SetActiveEx(false)
    self.ImgUnlook.gameObject:SetActiveEx(true)
    self.InFID.text = ""
    self.ClearPassword = ""
    self:SetLookStatus()
    self.LoginCallback = loginCallback
    self.CancelCallback = cancelCallback
end

function this:OnLogin()
    local account = self.InFID.text
    local pass = self.InFPassword.text
    local callback = self.LoginCallback

    if #account < 1 or #pass < 1 then
        XUiManager.TipError("アカウントまたはパスワードは空です")
        return
    end

    XLuaUiManager.Close("UiAccountSign")
    if callback then
        callback(account, pass)
    end
end


function this:OnCloseLogin()
    XLuaUiManager.Close("UiAccountSign")
    if self.CancelCallback then
        self.cancelCallback()
    end
end

function this:OnLookPassword()
    self.LookStatus = LookStatus.Switch - self.LookStatus
    self:SetLookStatus()
end

function this:SetLookStatus()
    if self.LookStatus == LookStatus.Clear then
        self.InFPassword.contentType = CS.UnityEngine.UI.InputField.ContentType.Standard
    else
        self.InFPassword.contentType = CS.UnityEngine.UI.InputField.ContentType.Password
    end
    self.ImgLook.gameObject:SetActiveEx(self.LookStatus == LookStatus.Clear)
    self.ImgUnlook.gameObject:SetActiveEx(self.LookStatus == LookStatus.Pass)
    self.ClearPassword = self.InFPassword.text
    self.InFPassword.text = ""
    self.InFPassword.text = self.ClearPassword
end