---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/7/11 17:43
---

local MAX_PROGRESS = 3
local EFFECT_PLAY_TIME = 1

local ENUM_PANEL_STATE = {
    Normal = 1,
    Effected = 2,
}

local XUiGoldenMinerSlotScoreGrid = require("XUi/XUiGoldenMiner/Grid/XUiGoldenMinerSlotScoreGrid")

---@class XUiGoldenMinerSlotScorePanel : XUiNode
---@field _SlotScoreGrid XUiGoldenMinerSlotScoreGrid[]
local XUiGoldenMinerSlotScorePanel = XClass(XUiNode, "XUiGoldenMinerSlotScorePanel")

function XUiGoldenMinerSlotScorePanel:OnStart()
    self:InitData()
    self:InitUi()

    self:_AddEventListener()
end

function XUiGoldenMinerSlotScorePanel:OnDestroy()
    self:_RemoveEventListener()
end

function XUiGoldenMinerSlotScorePanel:_AddEventListener()
    XEventManager.AddEventListener(XEventId.EVENT_GOLDEN_MINER_GAME_SLOT_SCORE_DATA_CHANGED, self.Refresh, self)
end

function XUiGoldenMinerSlotScorePanel:_RemoveEventListener()
    XEventManager.RemoveEventListener(XEventId.EVENT_GOLDEN_MINER_GAME_SLOT_SCORE_DATA_CHANGED, self.Refresh, self)
end

function XUiGoldenMinerSlotScorePanel:InitData()
    self._stoneTypeListCatch = nil
    self._PanelState = ENUM_PANEL_STATE.Normal
end

function XUiGoldenMinerSlotScorePanel:InitUi()
    self._SlotScoreGrid = {}
    for i = 1, MAX_PROGRESS do
        if i == 1 then
            table.insert(self._SlotScoreGrid, XUiGoldenMinerSlotScoreGrid.New(self.GridSlotMachine, self))
        else
            table.insert(self._SlotScoreGrid, XUiGoldenMinerSlotScoreGrid.New(XUiHelper.Instantiate(self.GridSlotMachine, self.GridPanel), self))
        end
        
        local settleEffect = self["SettleEffect" .. i]
        if settleEffect then
            settleEffect.gameObject:SetActiveEx(false)
        end
    end
end

function XUiGoldenMinerSlotScorePanel:Refresh(stoneTypeList, isSettle, sameStoneIndexSet)
    if self._PanelState == ENUM_PANEL_STATE.Effected then
        self._stoneTypeListCatch = stoneTypeList
    else
        self:_RefreshIcons(stoneTypeList)
        if isSettle then
            self:_PlayEffect(sameStoneIndexSet)

            self:Tween(EFFECT_PLAY_TIME, function()
            end, function()
                self:_HideEffect()
                self:_RefreshIcons(self._stoneTypeListCatch)
                self._PanelState = ENUM_PANEL_STATE.Normal
            end)

            self._PanelState = ENUM_PANEL_STATE.Effected
        end
    end
end

function XUiGoldenMinerSlotScorePanel:_RefreshIcons(stoneTypeList)
    for i = 1, MAX_PROGRESS do
        self._SlotScoreGrid[i]:RefreshIcon(stoneTypeList[i])
    end
end

function XUiGoldenMinerSlotScorePanel:_PlayEffect(sameStoneIndexSet)
    local count = 0
    for i = 1, MAX_PROGRESS do
        if sameStoneIndexSet[i] then
            count = count + 1
            self._SlotScoreGrid[i]:ShowSameEffect()
        else
            self._SlotScoreGrid[i]:ShowDiffEffect()
        end
    end

    if count == 0 then count = 1 end
    local settleEffect = self["SettleEffect" .. count]
    if settleEffect then
        settleEffect.gameObject:SetActiveEx(true)
    end

    if self.SettleEffectRoot then
        self.SettleEffectRoot.gameObject:SetActiveEx(true)
    end
end

function XUiGoldenMinerSlotScorePanel:_HideEffect()
    for i = 1, MAX_PROGRESS do
        self._SlotScoreGrid[i]:HideAllEffect()
        local settleEffect = self["SettleEffect" .. i]
        if settleEffect then
            settleEffect.gameObject:SetActiveEx(false)
        end
    end
    if self.SettleEffectRoot then
        self.SettleEffectRoot.gameObject:SetActiveEx(false)
    end
end

return XUiGoldenMinerSlotScorePanel