---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/2/1 16:19
---

XMergeAppEventChecker = {}
local this = XMergeAppEventChecker
local Helper = CS.XMergeHelper

local checkCsharpList =
{
    {"XApplication/SplashController.cs", "APPEVENT_LOGO_IOS"},
    {"XApplication/SplashController.cs", "APPEVENT_WORDS"},
    {"XManager/XFileManager.cs", "APPEVENT_VERSION_CHECKING_START"},
    {"XManager/XFileManager.cs", "APPEVENT_VERSION_CHECKING_END"},
    {"XManager/XFileManager.cs", "APPEVENT_RESOURCE_DOWNLOAD_START"},
    {"XApplication/XApplication.cs", "APPEVENT_GAME_INITIALIZE"},
    {"XApplication/XObbChecker.cs", "APPEVENT_SKIP_PV"},
}

local checkLuaList =
{
    {"XUi/XUiLogin/XUiLoginAgreePanel.lua", "APPEVENT_GAME_PRIVACY"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_CHANGE_ACCOUNT"},
    {"XManager/XHgSdkManager.lua", "APPEVENT_SDK_INITIALIZE"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_SDK_LOGIN"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_ANIM_START_1"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_ANIM_START_2"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_COMPLETED_REGISTRATION_1"},
    {"XUi/XUiLogin/XUiLogin.lua", "APPEVENT_COMPLETED_REGISTRATION_2"},
    {"XManager/XFubenManager.lua", "APPEVENT_FIRST_BATTLE_FINISH"},
    {"XManager/XFubenManager.lua", "APPEVENT_SECOND_BATTLE_END"},
    {"XManager/XGuideManager.lua", "APPEVENT_THIRD_BATTLE_END"},
    {"XManager/XTaskManager.lua", "APPEVENT_NEWBEE_AND_TASK"},
    {"XManager/XPayManager.lua", "APPEVENT_PURCHASED"},
    {"XManager/XPayManager.lua", "APPEVENT_FIRST_BUY"},
    {"XUi/XUiDraw/XUiDrawControl.lua", "APPEVENT_DRAWS_ROLE_10_1"},
    {"XUi/XUiDraw/XUiDrawControl.lua", "APPEVENT_DRAWS_ROLE_10_2"},
    {"XUi/XUiDraw/XUiDrawControl.lua", "APPEVENT_DRAWS_WEAPON_10_1"},
    {"XUi/XUiDraw/XUiDrawControl.lua", "APPEVENT_DRAWS_WEAPON_10_2"},
    {"XUi/XUiDraw/XUiDrawControl.lua", "APPEVENT_DRAWS_LIMIT_10"},
    {"XManager/XPurchaseManager.lua", "APPEVENT_TOTAL_PURCHASE"},
    {"XManager/XPayManager.lua", "APPEVENT_REDEEMED_AND_MONTHCARD"},
    {"XEntity/XPlayer.lua", "APPEVENT_LEVEL"},
    {"XUi/XUiTask/XDynamicDailyTask.lua", "APPEVENT_WAR_AND_PAINGAGE"},
    {"XManager/XMedalManager.lua", "APPEVENT_BADGE"},

}

function this.Check()
    for _, v in pairs(checkCsharpList) do
        if not v[1] or not v[2] then
            XLog.Error("请检查XMergeAppEventChecker CheckCsharpList 确保数组中都含有两个元素")
        else
            local r = Helper.CheckCSharp(v[1], "CheckPoint:\\s+" .. v[2])
            if not r then
                XLog.Error("<color=red>" .. v[1] .. " 文件缺少埋点 " .. v[2] .. "</color>")
            end
        end
    end

    for _, v in pairs(checkLuaList) do
        if not v[1] or not v[2] then
            XLog.Error("请检查XMergeAppEventChecker CheckLuaList 确保数组中都含有两个元素")
        else
            local r = Helper.CheckLua(v[1], "CheckPoint:\\s+" .. v[2])
            if not r then
                XLog.Error("<color=red>" .. v[1] .. " 文件缺少埋点 " .. v[2] .. "</color>")
            end
        end
    end
end