---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 17:56
---

---@class XNonogramStage
local XNonogramStage = XClass(nil, "XNonogramStage")

function XNonogramStage:Ctor()
    self:InitData()
end

function XNonogramStage:InitData()
    self._StageId = 0
    self._StageStatus = XEnumConst.Nonogram.NonogramStageStatus.None
end

function XNonogramStage:UpdateData(data)
    self._StageId = data.StageId
    self._StageStatus = data.StageStatus
end

function XNonogramStage:GetStageId()
    return self._StageId
end

function XNonogramStage:GetStageStatus()
    return self._StageStatus
end

return XNonogramStage