---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 17:56
---

local XNonogramStage = require("XModule/XNonogram/DataEntity/XNonogramStage")
---@class XNonogramChapter
local XNonogramChapter = XClass(nil, "XNonogramChapter")

function XNonogramChapter:Ctor()
    self:InitData()
end

function XNonogramChapter:InitData()
    self._ChapterId = 0
    self._CurStageId = 0
    self._StageList = {}
    self._IsUnlockCg = false
    self._ChapterStatus = XEnumConst.Nonogram.NonogramChapterStatus.Lock
end

function XNonogramChapter:UpdateData(data)
    self._ChapterId = data.ChapterId
    self._CurStageId = data.CurStageId
    self._ChapterStatus = data.ChapterStatus
    self._StageList = {}
    for _, stageInfo in ipairs(data.StageList) do
        local stageData = XNonogramStage.New()
        stageData:UpdateData(stageInfo)
        table.insert(self._StageList, stageData)
    end
end

function XNonogramChapter:GetChapterId()
    return self._ChapterId
end

function XNonogramChapter:GetCurStageId()
    return self._CurStageId
end

function XNonogramChapter:GetIsUnlockCg()
    return self._ChapterStatus == XEnumConst.Nonogram.NonogramChapterStatus.Reward
end

function XNonogramChapter:GetChapterStatus()
    return self._ChapterStatus
end

function XNonogramChapter:GetStageList()
    return self._StageList
end

return XNonogramChapter