---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/8/1 17:56
---

local XNonogramChapter = require("XModule/XNonogram/DataEntity/XNonogramChapter")
---@class XNonogramDataDb
local XNonogramDataDb = XClass(nil, "XNonogramDataDb")

function XNonogramDataDb:Ctor()
    self:InitData()
end

function XNonogramDataDb:InitData()
    self._ActivityId = 0
    self._ChaptersDir = {}
end

function XNonogramDataDb:UpdateData(data)
    self._ActivityId = data.ActivityId
    self._ChaptersDir = {}
    for _, chapterInfo in ipairs(data.Chapters) do
        ---@type XNonogramChapter
        local chapterData = XNonogramChapter.New()
        chapterData:UpdateData(chapterInfo)
        self._ChaptersDir[chapterData:GetChapterId()] = chapterData
    end
end

function XNonogramDataDb:UpdateChapterData(data)
    local chapterId = data.ChapterId
    if not self._ChaptersDir[chapterId] then
        self._ChaptersDir[chapterId] = XNonogramChapter.New()
    end
    
    self._ChaptersDir[chapterId]:UpdateData(data)
end

function XNonogramDataDb:GetActivityId()
    return self._ActivityId
end

function XNonogramDataDb:GetChapterDir()
    return self._ChaptersDir
end

function XNonogramDataDb:GetChapterInfo(chapterId)
    return self._ChaptersDir[chapterId]
end

return XNonogramDataDb