---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/4/12 10:33
---

---@class XUiDormAutoEventRewardsTipRewardGrid : XUiNode
local XUiDormAutoEventRewardsTipRewardGrid = XClass(XUiNode, "XUiDormAutoEventRewardsTipRewardGrid")

function XUiDormAutoEventRewardsTipRewardGrid:OnStart()
    self:RegisterBtnListener()
end

function XUiDormAutoEventRewardsTipRewardGrid:RegisterBtnListener()
    XUiHelper.RegisterClickEvent(self, self.BtnItemTip, function()
        self:OnBtnRewardClick()
    end)
end

function XUiDormAutoEventRewardsTipRewardGrid:OnBtnRewardClick()
    if not self._RewardGoodsInfo then
        return
    end
    
    XLuaUiManager.Open("UiTip", self._RewardGoodsInfo.TemplateId)
end

function XUiDormAutoEventRewardsTipRewardGrid:OnRefresh(rewardGoodInfos)
    if not rewardGoodInfos then
        return
    end

    self._RewardGoodsInfo = rewardGoodInfos
    self:RefreshRewardGoods()
end

--local rewardInfo = {
--    Id = rewardGood.Id,
--    TemplateId = rewardGood.TemplateId,
--    Count = rewardGood.Count,
--    Quality = rewardGood.Quality
--}
function XUiDormAutoEventRewardsTipRewardGrid:RefreshRewardGoods()
    local iconPath = XDataCenter.ItemManager.GetItemIcon(self._RewardGoodsInfo.TemplateId)
    local quality = XDataCenter.ItemManager.GetItemQuality(self._RewardGoodsInfo.TemplateId)
    local count = self._RewardGoodsInfo.Count

    self.RImgIcon:SetRawImage(iconPath)
    self.TxtCount.text = CsXTextManagerGetText("DormEventAutoRewardCountFormatStr", count)
    XUiHelper.SetQualityIcon(nil, self.ImgIconQuality, quality)
end

return XUiDormAutoEventRewardsTipRewardGrid