---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/4/12 9:57
---
local TWEEN_ANI_MIN_DURATION = 0.8
local TWEEN_ANI_MAX_DURATION = 1.5

---@class XUiDormAutoEventRewardsTipCharGrid : XUiNode
local XUiDormAutoEventRewardsTipCharGrid = XClass(XUiNode, "XUiDormAutoEventRewardsTipCharGrid")

function XUiDormAutoEventRewardsTipCharGrid:OnRefresh(characterMoodChange)
    if not characterMoodChange then
        return
    end

    self._CharacterMoodChange = characterMoodChange
    self:RefreshCharacterMood()
end

function XUiDormAutoEventRewardsTipCharGrid:RefreshCharacterMood()
    local characterIconPath = XDormConfig.GetCharacterStyleConfigQIconById(self._CharacterMoodChange.CharacterId)
    local characterMood = XDataCenter.DormManager.GetMoodById(self._CharacterMoodChange.CharacterId)

    self.Members:SetRawImage(characterIconPath)
    self.TxtMoodNum.text = self._CharacterMoodChange.AfterMoodValue
    self.TxtMoodNum.color = XDormConfig.GetMoodStateColor(characterMood)
    self.TxtNum.text = self._CharacterMoodChange.MoodChangeValue
    
end

function XUiDormAutoEventRewardsTipCharGrid:PlayTweenAnimation()
    --local characterMood = XDataCenter.DormManager.GetMoodById(self._CharacterMoodChange.CharacterId)
    local duration = self._CharacterMoodChange.MoodChangeValue < 10 and TWEEN_ANI_MIN_DURATION or TWEEN_ANI_MAX_DURATION
    self:Tween(duration, function(t)
        self.TxtMoodNum.text = math.floor(self._CharacterMoodChange.AfterMoodValue + self._CharacterMoodChange.MoodChangeValue * t)
    end, function()
        self.TxtMoodNum.text = self._CharacterMoodChange.AfterMoodValue + self._CharacterMoodChange.MoodChangeValue
    end)
end

return XUiDormAutoEventRewardsTipCharGrid