---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/11 21:04
---
local XUiBattleRoleRoomDefaultProxy = require("XUi/XUiNewRoomSingle/XUiBattleRoleRoomDefaultProxy")
local XUiBattleRoomRoleDetailSucceedBossProxy = require("XUi/XUiSucceedBoss/BattleRoleRoom/XUiBattleRoomRoleDetailSucceedBossProxy")

local XUiBattleRoleRoomSucceedBossProxy = XClass(XUiBattleRoleRoomDefaultProxy, "XUiBattleRoleRoomSucceedBossProxy")

function XUiBattleRoleRoomSucceedBossProxy:GetRoleDetailProxy()
    return XUiBattleRoomRoleDetailSucceedBossProxy
end

function XUiBattleRoleRoomSucceedBossProxy:AOPOnStartAfter(rootUi)
    self.RootUi = rootUi
    rootUi.BtnTeamPrefab.gameObject:SetActiveEx(XMVCA.XSucceedBoss:CheckCanChangeTeamEntity())
    --rootUi.BtnGarrisonBuff.gameObject:SetActiveEx(XMVCA.XSucceedBoss:CheckCanCheckGarrisonInfo())
    rootUi.BtnGarrisonBuff.gameObject:SetActiveEx(false)
    rootUi.BtnAuto.gameObject:SetActiveEx(XMVCA.XSucceedBoss:CheckChapterStageCanSweep())
    self:AutoRegisterListener()
end

function XUiBattleRoleRoomSucceedBossProxy:AutoRegisterListener()
    XUiHelper.RegisterClickEvent(self, self.RootUi.BtnGarrisonBuff, self.OnBtnGarrisonBuffClick)
    XUiHelper.RegisterClickEvent(self, self.RootUi.BtnAuto, self.OnBtnAutoClick, nil, true, 0.5)
end

function XUiBattleRoleRoomSucceedBossProxy:OnBtnGarrisonBuffClick()
    XLuaUiManager.Open("UiSucceedBossPopupGarrisonDetail")
end

function XUiBattleRoleRoomSucceedBossProxy:OnBtnAutoClick()
    -- 检查编队是否合法
    if not self:CheckTeamValidAndTip() then
        return
    end

    local team = self.RootUi.Team

    XMVCA.XSucceedBoss:RequestSucceedBossSweep(team:GetCharacterIdsOrder(), team:GetRobotIdsOrder(), team:GetCaptainPos(), team:GetFirstFightPos(), function(settleResult)
        self.RootUi:Close()
    end)
end

---@param battleRoleRoom XUiBattleRoleRoom
function XUiBattleRoleRoomSucceedBossProxy:AOPOnClickFight(battleRoleRoom)
    -- 检查编队是否合法
    if not self:CheckTeamValidAndTip() then
        return true
    end
    
    --每个章节的首个关卡，玩家在选完角色之后，点“ 进入战斗” 如果队伍中有与弱点不一致的角色 ，就弹窗提示“队伍中有与关卡弱点不一致的角色，是否继续进入战斗”，点击确定进入关卡，点击取消关闭弹窗返回战斗准备界面，勾选“今日不再提示”，则今日内不再弹出此弹窗。
    local progress = XMVCA.XSucceedBoss:GetStageProgressIndex()
    if progress == 1 then
        if XMVCA.XSucceedBoss:CheckWeaknessUnuseful(battleRoleRoom.Team) then
            XUiManager.ShowTodayNoMoreTips({
                Content = CS.XTextManager.GetText("SucceedBossWeaknessUnuseful"),
                Key = "SucceedBossCheckWeaknessUnuseful",
                Callback = function()
                    battleRoleRoom:EnterFight()
                end
            })
            return true
        end
    end

    return false
end

-- 获取有效的EntityId列表(服务器在驻守成员后不会修改并更新当前编队，要筛选出未驻守的成员才是真正的编队数据)
function XUiBattleRoleRoomSucceedBossProxy:GetValidEntityIdList()
    local curTeam = XMVCA.XSucceedBoss:GetTeam()
    local garrisonEntityIds = XMVCA.XSucceedBoss:GetGarrisonEntityIds()
    local entityIds = curTeam:GetEntityIds()
    local validEntityIds = {}
    for _, entityId in pairs(entityIds) do
        if garrisonEntityIds[entityId] == nil then
            table.insert(validEntityIds, entityId)
        end
    end

    return validEntityIds
end

function XUiBattleRoleRoomSucceedBossProxy:CheckTeamValidAndTip()
    local isTeamValid, tipTextKey = XMVCA.XSucceedBoss:CheckTeamValid()
    if not isTeamValid then
        XUiManager.TipText(tipTextKey)
    end

    return isTeamValid
end

return XUiBattleRoleRoomSucceedBossProxy