---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/19 14:22
---

local XUiBattleRoomRoleDetailDefaultProxy = require("XUi/XUiNewRoomSingle/XUiBattleRoomRoleDetailDefaultProxy")
local XUiBattleRoomRoleGridSucceedBoss = require("XUi/XUiSucceedBoss/BattleRoleRoom/XUiBattleRoomRoleGridSucceedBoss")
local XUiBattleRoomRoleDetailSucceedBossProxy = XClass(XUiBattleRoomRoleDetailDefaultProxy, 'XUiBattleRoomRoleDetailSucceedBossProxy')

function XUiBattleRoomRoleDetailSucceedBossProxy:GetEntities()
    if XMVCA.XSucceedBoss:CheckCanChangeTeamEntity() then
        local ownCharacterList = XMVCA.XCharacter:GetOwnCharacterList()
        local robotList = XMVCA.XSucceedBoss:GetActivityRobotsEntityList()
        return XTool.MergeArray(ownCharacterList, robotList)
    else
        -- 不能更换编队时，只显示当前编队
        return XMVCA.XSucceedBoss:GetTotalTeamEntityList()
    end
end

function XUiBattleRoomRoleDetailSucceedBossProxy:GetGridProxy()
    return XUiBattleRoomRoleGridSucceedBoss
end

function XUiBattleRoomRoleDetailSucceedBossProxy:AOPSetJoinBtnIsActiveBefore(rootUi)
    local isCanChangeTeamEntity = XMVCA.XSucceedBoss:CheckCanChangeTeamEntity()
    if not isCanChangeTeamEntity then
        rootUi.BtnJoinTeam.gameObject:SetActiveEx(false)
        rootUi.BtnQuitTeam.gameObject:SetActiveEx(false)
        return true
    end

    return false
end

return XUiBattleRoomRoleDetailSucceedBossProxy