---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/19 15:55
---

local XUiBattleRoomRoleGrid = require("XUi/XUiNewRoomSingle/XUiBattleRoomRoleGrid")
local XUiBattleRoomRoleGridSucceedBoss = XClass(XUiBattleRoomRoleGrid, "XUiBattleRoomRoleGridSucceedBoss")

function XUiBattleRoomRoleGridSucceedBoss:SetCharacterViewModel(characterViewModel)
    self.Super.SetCharacterViewModel(self, characterViewModel)
    self.PanelGarrison.gameObject:SetActiveEx(XMVCA.XSucceedBoss:CheckEntityIdIsGarrisoned(self.Character:GetId()))
end

return XUiBattleRoomRoleGridSucceedBoss