---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/2/1 15:09
---

XMergeChecker = {}

function XMergeChecker.Check()
    XLog.Error("<color=red>开始检查搬运情况</color>");
    XLog.Error("<color=red>=============</color>");
    CS.XMergeChecker.Check()
    XMergeAppEventChecker.Check()
    XLog.Error("<color=red>=============</color>");
    XLog.Error("<color=red>搬运情况检查结束</color>");
end