---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 17:08
---

---@class XSucceedBossCharacterInfoData
local XSucceedBossCharacterInfoData = XClass(nil, "XSucceedBossCharacterInfoData")

function XSucceedBossCharacterInfoData:Ctor()
    self.CharacterId = 0
    self.RobotId = 0
    self.HpPercent = 0
    self.Energy = 0
end

function XSucceedBossCharacterInfoData:UpdateData(data)
    self.CharacterId = data.CharacterId
    self.RobotId = data.RobotId
    self.HpPercent = data.HpPercent
    self.Energy = data.Energy
end

function XSucceedBossCharacterInfoData:GetCharacterId()
    return self.CharacterId
end

function XSucceedBossCharacterInfoData:GetRobotId()
    return self.RobotId
end

function XSucceedBossCharacterInfoData:GetHpPercent()
    return self.HpPercent
end

function XSucceedBossCharacterInfoData:GetEnergy()
    return self.Energy
end

return XSucceedBossCharacterInfoData