---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 16:50
---

local XSucceedBossChapterSelectMonsterData = require("XModule/XSucceedBoss/DataEntity/XSucceedBossChapterSelectMonsterData")

---@class XSucceedBossChapterData
local XSucceedBossChapterData = XClass(nil, "XSucceedBossChapterData")

function XSucceedBossChapterData:Ctor()
    self.ChapterId = 0
    self.MaxScore = 0
    self.SelectMonsters = {}
end

function XSucceedBossChapterData:UpdateData(data)
    self.ChapterId = data.ChapterId
    self.MaxScore = data.MaxScore

    if not XTool.IsTableEmpty(data.SelectMonsterInfos) then
        for monsterId, monsterData in pairs(data.SelectMonsterInfos) do
            if XTool.IsTableEmpty(self.SelectMonsters[monsterId]) then
                self.SelectMonsters[monsterId] = XSucceedBossChapterSelectMonsterData.New()
            end

            self.SelectMonsters[monsterId]:UpdateData(monsterData)
        end
    end
end

function XSucceedBossChapterData:GetChapterId()
    return self.ChapterId
end

function XSucceedBossChapterData:GetMaxScore()
    return self.MaxScore
end

function XSucceedBossChapterData:GetSelectMonsters()
    return self.SelectMonsters
end

return XSucceedBossChapterData