---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 16:50
---

---@class XSucceedBossStageInfoData
local XSucceedBossStageInfoData = XClass(nil, "XSucceedBossStageInfoData")

function XSucceedBossStageInfoData:Ctor()
    self.StageId = 0
    self.StageIndex = 0
    self.MonsterId = 0
    self.MonsterLevel = 0
    self.DefendCharacterId = 0
end

function XSucceedBossStageInfoData:UpdateData(data)
    self.StageId = data.StageId
    self.StageIndex = data.StageIndex
    self.MonsterId = data.MonsterId
    self.MonsterLevel = data.MonsterLevel
    -- 驻守的角色Id
    self.DefendCharacterId = data.DefendCharacterId
    -- 驻守的机器人Id
    self.DefendRobotId = data.DefendRobotId
end

function XSucceedBossStageInfoData:GetStageId()
    return self.StageId
end

function XSucceedBossStageInfoData:GetStageIndex()
    return self.StageIndex
end

function XSucceedBossStageInfoData:GetMonsterId()
    return self.MonsterId
end

function XSucceedBossStageInfoData:GetMonsterLevel()
    return self.MonsterLevel
end

function XSucceedBossStageInfoData:GetDefendCharacterId()
    return self.DefendCharacterId
end

function XSucceedBossStageInfoData:GetDefendRobotId()
    return self.DefendRobotId
end

return XSucceedBossStageInfoData