---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 16:50
---

---@class XSucceedBossSweepStageData
local XSucceedBossSweepStageData = XClass(nil, "XSucceedBossSweepStageData")

function XSucceedBossSweepStageData:Ctor()
    self.StageId = 0
    self.StageIndex = 0
    self.MonsterId = 0
    self.MonsterLevel = 0
end

function XSucceedBossSweepStageData:UpdateData(data)
    self.StageId = data.StageId
    self.StageIndex = data.StageIndex
    self.MonsterId = data.MonsterId
    self.MonsterLevel = data.MonsterLevel
end

function XSucceedBossSweepStageData:GetStageId()
    return self.StageId
end

function XSucceedBossSweepStageData:GetStageIndex()
    return self.StageIndex
end

function XSucceedBossSweepStageData:GetMonsterId()
    return self.MonsterId
end

function XSucceedBossSweepStageData:GetMonsterLevel()
    return self.MonsterLevel
end

return XSucceedBossSweepStageData