---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 16:50
---

---@class XSucceedBossMonsterData
local XSucceedBossMonsterData = XClass(nil, "XSucceedBossMonsterData")

function XSucceedBossMonsterData:Ctor()
    self.MonsterId = 0
    self.Level = 0
end

function XSucceedBossMonsterData:UpdateData(data)
    self.MonsterId = data.MonsterId
    self.Level = data.Level
end

function XSucceedBossMonsterData:GetMonsterId()
    return self.MonsterId
end

function XSucceedBossMonsterData:GetLevel()
    return self.Level
end

return XSucceedBossMonsterData