---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/6/3 17:01
---

---@class XSucceedBossTeamInfoData
local XSucceedBossTeamInfoData = XClass(nil, "XSucceedBossTeamInfoData")

function XSucceedBossTeamInfoData:Ctor()
    self.CharacterIds = { 0, 0, 0 }
    self.RobotIds = { 0, 0, 0 }
    self.CaptainPos = 1
    self.FirstFightPos = 1
    self.SelectedGeneralSkill = 0
end

function XSucceedBossTeamInfoData:UpdateData(data)
    self.CharacterIds = data.CharacterIds
    self.RobotIds = data.RobotIds
    self.CaptainPos = data.CaptainPos
    self.FirstFightPos = data.FirstFightPos
    self.SelectedGeneralSkill = data.SelectedGeneralSkill
end

function XSucceedBossTeamInfoData:GetCharacterIds()
    return self.CharacterIds
end

function XSucceedBossTeamInfoData:GetRobotIds()
    return self.RobotIds
end

function XSucceedBossTeamInfoData:GetCaptainPos()
    return self.CaptainPos
end

function XSucceedBossTeamInfoData:GetFirstFightPos()
    return self.FirstFightPos
end

function XSucceedBossTeamInfoData:GetSelectedGeneralSkill()
    return self.SelectedGeneralSkill
end

return XSucceedBossTeamInfoData