return {
    Cams = {
        {
            ref = 0,
            placeId = 9998,
            agent = 0,
            follow = 0, ---self._localPlayerNpcId,
            aim = 0,
            callBack = nil,
        }
    },
    Switches = {
        {
            placeId = 1,
            agent = nil,
            object = nil, ---self,
            func = nil, ---self.GateControl,
            param = nil,
            triggerTimes = 1,
        },
        {
            placeId = 5,
            agent = nil,
            object = nil, ---self,
            func = nil, ---self.EnableAnchor,
            param = 6,
            triggerTimes = 1,
        },
        {
            placeId = 9,
            agent = nil,
            object = nil, ---self,
            func = nil, ---self.EnableAnchor,
            param = 10,
            triggerTimes = 1,
        }
    },
    Anchors = {
        {
            placeId = 2,
            agent = nil,
            defaultEnable = false,
            type = 24,
        },
        {
            placeId = 3,
            agent = nil,
            defaultEnable = false,
            type = 23,
        },
        {
            placeId = 4,
            agent = nil,
            defaultEnable = false,
            type = 23,
        },
        {
            placeId = 6,
            agent = nil,
            defaultEnable = false,
            type = 24,
        },
        {
            placeId = 7,
            agent = nil,
            defaultEnable = false,
            type = 23,
        },
        {
            placeId = 8,
            agent = nil,
            defaultEnable = true,
            type = 24,
        },
        {
            placeId = 10,
            agent = nil,
            defaultEnable = false,
            type = 23,
        },
        {
            placeId = 11,
            agent = nil,
            defaultEnable = true,
            type = 24,
        },
        {
            placeId = 12,
            agent = nil,
            defaultEnable = true,
            type = 24,
        },
    },
    Guides = {
        [1] = {
            GuideId = 12001,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 2,
        },
        [2] = {
            GuideId = 12002,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 3,
        },
        [3] = {
            GuideId = 12003,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 4,
        },
        [4] = {
            GuideId = 12004,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 5,
        },
        [5] = {
            GuideId = 12005,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 1, -- levelProgress
        },
        [10] = {
            GuideId = 12010,
            ClickKey = ENpcOperationKey.GuideClick,
            Next = 12,
            --因为下一句是常驻的，因此此句结束算步骤完成
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 2,
        },
        [11] = {
            GuideId = 12011,
            Next = 12,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [12] = {
            GuideId = 12012,
        },
        [20] = {
            GuideId = 12020,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 21,
            CallBackObj = nil,
            CallBackFuncName = "FocusOnSceneObj",
            CallBackParam = 1,
        },
        [21] = {
            GuideId = 12021,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 22,
        },
        [22] = {
            GuideId = 12022,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 3,
        },
        [30] = {
            GuideId = 12030,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 31,
        },
        [31] = {
            GuideId = 12031,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 32,
        },
        [32] = {
            GuideId = 12032,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Next = 33,
            CallBackFuncName = "Step4EnableAnchors",
        },
        [33] = {
            GuideId = 12033,
            Next = 34,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [34] = {
            GuideId = 12034,
            Next = 35,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [35] = {
            GuideId = 12035,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackFuncName = "Step4EnableFocusListen",
        },
        [37] = {
            GuideId = 12037,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 4,
        },
        [40] = {
            GuideId = 12040,
            Next = 41,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [41] = {
            GuideId = 12041,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "Step5ShowSwitchTips",
        },
        [42] = {
            GuideId = 12042,
            Next = 43,
            CallBackObj = nil,
            CallBackFuncName = "FocusOnSceneObj",
            CallBackParam = 1004,
        },
        [43] = {
            GuideId = 12043,
            Next = 44,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "Step5StartTraining",
        },
        [44] = {
            GuideId = 12044,
        },
        [45] = {
            GuideId = 12045,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 5,
        },
        [50] = {
            GuideId = 12050,
            Next = 51,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [51] = {
            GuideId = 12051,
            Next = 52,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [52] = {
            GuideId = 12052,
            Next = 53,
            ConversationSet = "Normal",
            ClickKey = ENpcOperationKey.NextStory,
        },
        [53] = {
            GuideId = 12053,
            Next = 54,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackFuncName = "Step6ShowFocusBtn",
        },
        [54] = {
            GuideId = 12054,
            Next = 55,
            ClickKey = ENpcOperationKey.GuideClick,
        },
        [55] = {
            GuideId = 12055,
            ClickKey = ENpcOperationKey.Spear,
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 6,
        },
        [60] = {
            GuideId = 12060,
            Next = 61,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [61] = {
            GuideId = 12061,
            Next = 62,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [62] = {
            GuideId = 12062,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackObj = nil,
            CallBackFuncName = "Step7AttackPractice",
        },
        [63] = {
            GuideId = 12063,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            Pause = true,
        },
        [64] = {
            GuideId = 12064,
            ClickKey = ENpcOperationKey.NextStory,
            CallBackObj = nil,
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 7,
            ConversationSet = "Normal",
            Pause = true,
        },
        [70] = {
            GuideId = 12070,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackFuncName = "Step8WaitingFly",
            Pause = true,
        },
        [71] = {
            GuideId = 12071,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackFuncName = "Step8WaitingAtk",
        },
        [72] = {
            GuideId = 12072,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Air",
            Next = 73,
        },
        [73] = {
            GuideId = 12073,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackFuncName = "Step8WaitingEliminate",
        },
        [74] = {
            GuideId = 12074,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Air",
            CallBackFuncName = "Step8WaitingZuma",
        },
        [75] = {
            GuideId = 12075,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackFuncName = "Step8WaitingColor",
        },
        [76] = {
            GuideId = 12076,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Air",
            CallBackFuncName = "FinishedGuideStep",
            CallBackParam = 8,
            Pause = true,
        },
        [80] = {
            GuideId = 12080,
            Next = 81,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [81] = {
            GuideId = 12081,
            Next = 82,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [82] = {
            GuideId = 12082,
            Next = 83,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [83] = {
            GuideId = 12083,
            Next = 84,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [84] = {
            GuideId = 12084,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackFuncName = "Step9BlueLockListen",
            Next = 86,
        },
--[[        [85] = {
            GuideId = 12085,
            Next = 86,
            ClickKey = ENpcOperationKey.GuideClick,
            CallBackFuncName = "Step9BlueLockListen",
        },]]
        [86] = {
            GuideId = 12086,
            Next = 87,
        },
        [87] = {
            GuideId = 12087,
            ClickKey = ENpcOperationKey.GuideClick,
            Pause = true,
        },
        [90] = {
            GuideId = 12090,
            Next = 91,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
        [91] = {
            GuideId = 12091,
            Next = 92,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
            CallBackFuncName = "Step9BlueLockListen",
        },
        [92] = {
            GuideId = 12092,
            Next = 87,
        },
        [990] = {
            GuideId = 12990,
            ClickKey = ENpcOperationKey.NextStory,
            ConversationSet = "Normal",
        },
    }
}
