---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyupeng.
--- DateTime: 2024/9/5 15:01
---

---@class UiNewbiePopup: XLuaUi
local XUiNewbiePopup = XLuaUiManager.Register(XLuaUi, "UiNewbiePopup")

function XUiNewbiePopup:OnAwake()
    
end

function XUiNewbiePopup:OnStart(continueExchangeFunc, cancelFunc)
    self.ContinueExchangeFunc = continueExchangeFunc
    self.CancelFunc = cancelFunc
    self:InitData()
    self:AutoRegisterBtnListener()
    self:Refresh()
end

function XUiNewbiePopup:OnDestroy()
    
end

function XUiNewbiePopup:InitData()
    self.SkipId = CS.XGame.ClientConfig:GetInt("UiNewbiePopupSkipId")
    self.TipText = CS.XGame.ClientConfig:GetString("UiNewbiePopupTipText")
end

function XUiNewbiePopup:AutoRegisterBtnListener()
    self.BtnCancelBg.CallBack = handler(self, self.OnBtnCancelBgClick)
    self.BtnYes.CallBack = handler(self, self.OnBtnYesClick)
    self.BtnCancel.CallBack = handler(self, self.OnBtnCancelClick)
    self.BtnNewbie.CallBack = handler(self, self.OnBtnNewbieClick)
end

function XUiNewbiePopup:OnBtnCancelBgClick()
    self:Close()
    if self.CancelFunc then
        self.CancelFunc()
    end
end

function XUiNewbiePopup:OnBtnYesClick()
    self:Close()
    if self.ContinueExchangeFunc then
        self.ContinueExchangeFunc()
    end
end

function XUiNewbiePopup:OnBtnCancelClick()
    self:Close()
    if self.CancelFunc then
        self.CancelFunc()
    end
end

function XUiNewbiePopup:OnBtnNewbieClick()
    if XTool.IsNumberValid(self.SkipId) then
        self:Close()
        if self.CancelFunc then
            self.CancelFunc()
        end
        XFunctionManager.SkipInterface(self.SkipId)
    end
end

function XUiNewbiePopup:Refresh()
    self.TxtTips.text = self.TipText or ""
end