local UIBindControl = {
    UiMail = ModuleId.XMail,
    UiFavoriteMailTag = ModuleId.XMail,
    XUiPanelCommonCharacterFilterV2P6 = ModuleId.XCharacter,
    UiCharacterV2P6 = ModuleId.XCharacter,
    XGridCharacterV2P6 = ModuleId.XCharacter,
    -- 装备
    UiEquipDetailChildV2P6 = ModuleId.XEquip,
    UiEquipDetailV2P6 = ModuleId.XEquip,
    UiEquipOverrunV2P6 = ModuleId.XEquip,
    UiEquipOverrunSelect = ModuleId.XEquip,
    UiEquipOverrunLevel = ModuleId.XEquip,
    UiEquipStrengthenV2P6 = ModuleId.XEquip,
    UiEquipStrengthenConsumptionV2P6 = ModuleId.XEquip,
    UiEquipCultureConfirm = ModuleId.XEquip,
    UiEquipResonanceSkillV2P6 = ModuleId.XEquip,
    UiEquipResonanceSelectV2P6 = ModuleId.XEquip,
    UiEquipResonanceSelectCharacterV2P6 = ModuleId.XEquip,
    UiEquipResonanceSelectEquipV2P6 = ModuleId.XEquip,
    UiEquipResonanceSkillChangeV2P6 = ModuleId.XEquip,
    UiEquipResonanceSkillPreview = ModuleId.XEquip,
    UiExhibitionOverclockingV2P6 = ModuleId.XEquip,
    UiEquipResonanceAwakeV2P6 = ModuleId.XEquip,
    UiEquipReplaceV2P6 = ModuleId.XEquip,
    UiEquipAwarenessReplaceV2P6 = ModuleId.XEquip,
    UiEquipSuitSkillV2P6 = ModuleId.XEquip,
    UiEquipPreviewV2P6 = ModuleId.XEquip,
    UiEquipDetailOther = ModuleId.XEquip,
    UiAwarenessOccupyProgress = ModuleId.XEquip,
    UiEquipDetailOther = ModuleId.XEquip,
    UiEquipAwarenessV2P6 = ModuleId.XEquip,
    --region 肉鸽3.0
    UiTheatre3Main = ModuleId.XTheatre3,
    UiTheatre3LvReward = ModuleId.XTheatre3,
    UiTheatre3Tips = ModuleId.XTheatre3,
    UiTheatre3Task = ModuleId.XTheatre3,
    UiTheatre3Master = ModuleId.XTheatre3,
    UiTheatre3Handbook = ModuleId.XTheatre3,
    UiTheatre3EquipmentChoose = ModuleId.XTheatre3,
    UiTheatre3SetBag = ModuleId.XTheatre3,
    UiTheatre3RecastSettlement = ModuleId.XTheatre3,
    UiTheatre3Settlement = ModuleId.XTheatre3,
    UiTheatre3BubbleEquipment = ModuleId.XTheatre3,
    UiTheatre3SuitTip = ModuleId.XTheatre3,
    UiTheatre3SettlementTip = ModuleId.XTheatre3,
    UiTheatre3Difficulty = ModuleId.XTheatre3,
    UiTheatre3Loading = ModuleId.XTheatre3,
    UiTheatre3EndLoading = ModuleId.XTheatre3,
    UiTheatre3EndTips = ModuleId.XTheatre3,
    UiTheatre3PlayMain = ModuleId.XTheatre3,
    UiTheatre3RewardChoose = ModuleId.XTheatre3,
    UiTheatre3Outpost = ModuleId.XTheatre3,
    UiTheatre3Prop = ModuleId.XTheatre3,
    UiTheatre3RoleRoom = ModuleId.XTheatre3,
    UiTheatre3TeamInstall = ModuleId.XTheatre3,
    UiTheatre3RoleRoomDetail = ModuleId.XTheatre3,
    UiTheatre3TipReward = ModuleId.XTheatre3,
    UiTheatre3SetDetail = ModuleId.XTheatre3,
    XUiTheatre3RoleRoomCharacterListGrid = ModuleId.XTheatre3,
    UiTheatre3ShopTips = ModuleId.XTheatre3,
    UiTheatre3UnlockTips = ModuleId.XTheatre3,
    --endregion
    --region 大转盘
    UiTurntableMain = ModuleId.XTurntable,
    UiTurntableLog = ModuleId.XTurntable,
    UiTurntableTask = ModuleId.XTurntable,
    UiGridTurntableProgressReward = ModuleId.XUiTurntable,
    --endregion
}
return UIBindControl